export { NAVS } from 'consts/navs'
export { CONTACTS } from 'consts/contacts'
export { MOCK_OPINIONS } from 'consts/mock_opinions'
export { MOCK_HERO } from 'consts/mock_hero'
export { MOCK_PRODUCTS } from 'consts/mock_products'
export { SOCIALS } from 'consts/socials'
export { FOOTER } from 'consts/footer'
